import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'
import About from "./about";
import Link from "next/link";
import Product from "../components/product";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <header className="p-3 text-bg-dark">
                <div className="container">
                    <div
                        className="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

                        <ul className="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                            <li>
                                < Link className="nav-link px-2 text-white" href="/">Home</Link>
                            </li>
                            <li>
                                < Link className="nav-link px-2 text-white" href="/about">About</Link>
                            </li>
                        </ul>

                        {/*<form className="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">*/}
                        {/*    <input type="search" className="form-control form-control-dark text-bg-dark"*/}
                        {/*           placeholder="Search..." aria-label="Search"/>*/}
                        {/*</form>*/}

                        {/*<div className="text-end">*/}
                        {/*    <button type="button" className="btn btn-outline-light me-2">Login</button>*/}
                        {/*    <button type="button" className="btn btn-warning">Sign-up</button>*/}
                        {/*</div>*/}
                    </div>
                </div>
            </header>
            <Product/>
        </>

    )
}
